<?xml version="1.0" encoding="utf-8"?><Database Name="dranken" Class="drankenDBDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1MI50OM\SQLEXPRESS01;Initial Catalog=dranken;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="DrankRegistratie.Properties.Settings" SettingsPropertyName="drankenConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dranken" Member="drankens">
    <Type Name="dranken">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soort" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prijs" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>